### ISSUE TITLE
Repeat operations leaking through

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#23]
Could you please look into repeat operations "leaking through" into insert mode (a teensy bug).

Pressing c t r and then t (to type the letter t in insert mode) makes evil-snipe jumps to the next instance of r instead.

Note that something similar to this might be a feature, not a bug. If you meant to clear to amaz, but only got to czechoslovakian being able to press t again is a good thing.

(But this leads to inconsistent behavior if you meant to type the letter t. You could add a timeout so that t means repeat clear until 0.2 seconds for example, but this is a tiny thing not worth bothering with unless you want to. I think syl20bnr implemented a timeout in avy which might be worth looking at.)

**Comment by hlissner** [comment]
Sorry I'm noticing this just now. I'm a little out of the loop. I believe this was fixed in 160bf1a. I can't reproduce it now.

If you want more precise control over where the motion takes you, I'd recommend you look at [evil-easymotion](https://github.com/PythonNut/evil-easymotion) (mentioned in #25) — and [configure it for evil-snipe](https://github.com/PythonNut/evil-easymotion/wiki/Integrating-with-evil-snipe).

**Comment by endrebak** [comment]
It probably was fixed. This issue is ancient 😀
